name: colaborativa_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.2
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  shared_preferences: ^2.0.13  
  mask_text_input_formatter: ^2.3.0
  intl: ^0.17.0
  modx:
    path: ../../modx
  firebase_database: ^9.0.13
  dio: ^4.0.6
  flutter_modular: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/svg/

  fonts:
    - family: BalooDa2
      fonts:
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-Bold.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-ExtraBold.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-Medium.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-Regular.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-SemiBold.ttf
