name: colaborativa_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  freezed_annotation: ^2.0.3
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  shared_preferences: ^2.0.15
  mask_text_input_formatter: ^2.3.0
  intl: ^0.17.0
  firebase_database: ^9.0.15
  dio: ^4.0.6
  provider: ^6.0.3
  jiffy: ^5.0.0
  firebase_messaging: ^11.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/svg/

  fonts:
    - family: BalooDa2
      fonts:
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-Bold.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-ExtraBold.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-Medium.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-Regular.ttf
        - asset: assets/fonts/Baloo_Da_2/static/BalooDa2-SemiBold.ttf
